import React from 'react';
import 'katex/dist/katex.min.css';
import Latex from 'react-latex-next';
import { Play } from 'lucide-react';

export function KolmogorovComplexityContent() {
    return (
        <div className="prose prose-slate max-w-none">
            <h2 className="text-3xl font-bold text-slate-900 mb-6 flex items-center gap-3">
                Complexity and Generalization
                <span className="bg-indigo-100 text-indigo-700 text-sm px-3 py-1 rounded-full font-semibold">1.11.4</span>
            </h2>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
                The complexity of a model refers to its ability to fit a wide range of functions or data patterns. A key challenge in model design is to balance complexity with generalization, ensuring that the model performs well not only on the training data but also on unseen data. This section explores the concept of Kolmogorov complexity and how generalization bounds can be established for machine learning models, including transformers.
            </p>

            <h3 className="text-2xl font-semibold text-slate-800 mt-8 mb-4">Kolmogorov Complexity</h3>
            <p className="text-slate-700 leading-relaxed mb-4">
                Kolmogorov complexity, also known as algorithmic complexity, measures the complexity of an object (such as a string or a function) by the length of the shortest program that can produce that object on a universal Turing machine. Formally, the Kolmogorov complexity <Latex>{'$K(x)$'}</Latex> of a string <Latex>{'$x$'}</Latex> is defined as
            </p>

            <div className="bg-slate-50 p-6 rounded-2xl mb-6 shadow-inner overflow-x-auto text-center border border-slate-100">
                <Latex>{"$$K(x) = \\min\\{|p| : U(p) = x\\}$$"}</Latex>
            </div>

            <p className="text-slate-700 leading-relaxed mb-6">
                where <Latex>{'$U$'}</Latex> is a fixed universal Turing machine, <Latex>{'$p$'}</Latex> is a program that generates <Latex>{'$x$'}</Latex>, and <Latex>{'$|p|$'}</Latex> denotes the length of <Latex>{'$p$'}</Latex> in bits.
            </p>

            <p className="text-slate-700 leading-relaxed mb-6">
                Kolmogorov complexity provides a formal measure of the "compressibility" of an object. If <Latex>{'$x$'}</Latex> can be generated by a short program, it has low complexity; if the shortest program is nearly as long as <Latex>{'$x$'}</Latex> itself, the object is incompressible and has high complexity.
            </p>

            <h4 className="text-xl font-semibold text-slate-800 mb-3">Properties of Kolmogorov complexity:</h4>
            <ul className="list-disc pl-6 space-y-2 text-slate-700 mb-6">
                <li><strong className="text-slate-900">Incomputability:</strong> Kolmogorov complexity is not computable in general, meaning there is no algorithm that can determine the exact complexity of any given string.</li>
                <li><strong className="text-slate-900">Invariance:</strong> The complexity <Latex>{'$K_U(x)$'}</Latex> depends on the choice of the universal Turing machine <Latex>{'$U$'}</Latex>, but the difference between complexities for different choices of <Latex>{'$U$'}</Latex> is bounded by a constant independent of <Latex>{'$x$'}</Latex>.</li>
                <li><strong className="text-slate-900">Prefix Complexity:</strong> A variant of Kolmogorov complexity, called prefix complexity <Latex>{'$K_{prefix}(x)$'}</Latex>, considers only prefix-free programs (where no program is a prefix of another), and is used in areas such as information theory and coding.</li>
            </ul>

            <div className="bg-indigo-50 border-l-4 border-indigo-500 p-6 rounded-r-xl mb-6 shadow-[inset_0_1px_4px_rgba(0,0,0,0.02)]">
                <p className="text-slate-800 leading-relaxed mb-0">
                    <strong className="font-semibold text-indigo-900">Example:</strong> The string <Latex>{'$x = 01010101 \\dots 01$'}</Latex> (with length <Latex>{'$n$'}</Latex>) has low Kolmogorov complexity because it can be generated by a short program that outputs "01" repeatedly. In contrast, a random string of the same length would likely have high complexity, as it cannot be compressed into a shorter program.
                </p>
            </div>

            <p className="text-slate-700 leading-relaxed mb-6">
                Kolmogorov complexity provides a theoretical foundation for understanding the trade-off between model complexity and generalization. Models that are too complex may fit the training data perfectly but fail to generalize to new data (overfitting), while models that are too simple may underfit the data, missing important patterns.
            </p>

            <div className="bg-rose-50 border border-rose-100 p-6 rounded-2xl mb-8 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-24 h-24 bg-rose-200 rounded-bl-full opacity-20 -mr-4 -mt-4 transition-transform group-hover:scale-110"></div>
                <h4 className="text-lg font-bold text-rose-900 mb-3 flex items-center gap-2 relative z-10">
                    Remark (Kolmogorov Complexity and Overfitting)
                </h4>
                <p className="text-rose-800 text-sm leading-relaxed mb-0 relative z-10">
                    Let <Latex>{'$\\mathcal{H}$'}</Latex> be a hypothesis class and <Latex>{'$h \\in \\mathcal{H}$'}</Latex> be a hypothesis selected by a learning algorithm based on the training data <Latex>{'$\\mathcal{D}$'}</Latex>. If the Kolmogorov complexity <Latex>{'$K(h)$'}</Latex> is high relative to the complexity of the data <Latex>{'$K(\\mathcal{D})$'}</Latex>, the hypothesis <Latex>{'$h$'}</Latex> is more likely to overfit the data. Conversely, if <Latex>{'$K(h)$'}</Latex> is low, the hypothesis is more likely to generalize well.
                </p>
            </div>

            <button className="flex items-center gap-3 bg-indigo-50 text-indigo-700 px-6 py-4 rounded-2xl font-medium hover:bg-indigo-100 transition-all active:scale-[0.98] w-full border border-indigo-100 group shadow-sm">
                <div className="w-10 h-10 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center group-hover:bg-indigo-600 group-hover:text-white transition-colors">
                    <Play size={20} className="ml-1" />
                </div>
                <span>Audio Track: Kolmogorov Complexity & Compressibility</span>
            </button>
        </div>
    );
}

export function GeneralizationBoundsContent() {
    return (
        <div className="prose prose-slate max-w-none">
            <h3 className="text-2xl font-bold text-slate-900 mb-4 mt-8">Generalization Bounds</h3>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
                Generalization refers to the ability of a model to perform well on unseen data, not just on the data it was trained on. Generalization bounds provide theoretical guarantees on how well a model trained on a finite sample will perform on the overall data distribution.
            </p>

            <p className="text-slate-700 leading-relaxed mb-6">
                In the Probably Approximately Correct (PAC) learning framework, we seek to understand the conditions under which a learning algorithm can produce a hypothesis that, with high probability, performs close to optimally on the underlying distribution. Let <Latex>{'$\\mathcal{H}$'}</Latex> be a hypothesis class, <Latex>{'$D$'}</Latex> be the training data drawn from a distribution <Latex>{'$\\mathcal{D}$'}</Latex>, and <Latex>{'$\\epsilon$'}</Latex> be the allowable error. A hypothesis <Latex>{'$h$'}</Latex> is said to be identically <Latex>{'$\\epsilon$'}</Latex>-good if:
            </p>

            <div className="bg-slate-50 p-6 rounded-2xl mb-6 shadow-inner overflow-x-auto text-center border border-slate-100">
                <Latex>{"$$\\mathbb{P}_{x \\sim \\mathcal{D}}[h(x) \\neq f(x)] \\le \\epsilon$$"}</Latex>
            </div>

            <p className="text-slate-700 leading-relaxed mb-6">
                where <Latex>{'$f(x)$'}</Latex> is the true underlying function. The PAC learning framework provides bounds on the sample size <Latex>{'$m$'}</Latex> needed to guarantee that the learning algorithm produces an <Latex>{'$\\epsilon$'}</Latex>-good hypothesis with high probability.
            </p>

            <p className="text-slate-700 leading-relaxed mb-8">
                The Vapnik–Chervonenkis (VC) dimension is a measure of the capacity or complexity of a hypothesis class <Latex>{'$\\mathcal{H}$'}</Latex>. It is defined as the size of the largest set of points that can be shattered by <Latex>{'$\\mathcal{H}$'}</Latex>, where "shatter" means that for every possible labeling of the points, there exists a hypothesis in <Latex>{'$\\mathcal{H}$'}</Latex> that correctly classifies them.
            </p>

            <div className="bg-indigo-50 border border-indigo-100 p-6 rounded-2xl mb-8 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-200 rounded-bl-full opacity-20 -mr-8 -mt-8"></div>
                <h4 className="text-lg font-bold text-indigo-900 mb-3 relative z-10 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-indigo-500"></span>
                    Theorem 1.20 (Generalization Bound via VC Dimension)
                </h4>
                <p className="text-indigo-800 leading-relaxed mb-4 relative z-10">
                    Let <Latex>{'$\\mathcal{H}$'}</Latex> be a hypothesis class with VC dimension <Latex>{'$d_{VC}$'}</Latex>. Then, for any <Latex>{'$\\epsilon > 0$'}</Latex> and <Latex>{'$\\delta > 0$'}</Latex>, with probability at least <Latex>{'$1 - \\delta$'}</Latex>, the generalization error of a hypothesis <Latex>{'$h$'}</Latex> learned from <Latex>{'$m$'}</Latex> samples is bounded by:
                </p>
                <div className="bg-white/60 p-5 rounded-xl text-center shadow-sm relative z-10 border border-indigo-200/50 mb-4">
                    <Latex>{"$$\\mathbb{P}_{x \\sim \\mathcal{D}}[h(x) \\neq f(x)] \\le \\hat{\\epsilon} + \\mathcal{O}\\left(\\sqrt{\\frac{d_{VC} \\log(m/d_{VC}) + \\log(1/\\delta)}{m}}\\right)$$"}</Latex>
                </div>
                <p className="text-indigo-800 text-sm leading-relaxed mb-0 relative z-10">
                    where <Latex>{'$\\hat{\\epsilon}$'}</Latex> is the empirical error on the training set. This bound indicates that the generalization error decreases as the number of samples increases, and it depends on the complexity of the hypothesis class as measured by the VC dimension.
                </p>
            </div>

            <p className="text-slate-700 leading-relaxed mb-6">
                In transformers, the generalization ability is influenced by both the architecture's capacity (e.g., number of layers, attention heads) and the regularization techniques used during training. The VC dimension or similar complexity measures can be used to understand the trade-offs involved in designing transformer models that generalize well to new data. For a transformer model, one might analyze the VC dimension of the attention mechanism or the overall architecture to predict how well the model is likely to generalize based on the amount of training data available.
            </p>

            <button className="flex items-center gap-3 bg-indigo-50 text-indigo-700 px-6 py-4 rounded-2xl font-medium hover:bg-indigo-100 transition-all active:scale-[0.98] w-full border border-indigo-100 group shadow-sm mt-8">
                <div className="w-10 h-10 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center group-hover:bg-indigo-600 group-hover:text-white transition-colors">
                    <Play size={20} className="ml-1" />
                </div>
                <span>Audio Track: VC Dimension & Generalization Limits</span>
            </button>
        </div>
    );
}
